### ISSUE TITLE
Spring annotation should not be required in nested test class

### ISSUE THREAD

**Issue by jlink** [sbrannen/spring-test-junit5#14] opened 2017-09-08 06:33 UTC
```java
@SpringBootTest(...)
@ExtendWith(SpringExtension.class)
class OuterTests {
   @BeforeEach
   void init(@Autowired MyComponent component) {}

  @Test void test1() {}

  @Nested class InnerTests {
    @Test void test2() {}
  }
}
```

`test2` will fail due to component lookup failure in `init` unless the nested test class is also annotated with `@SpringBootTest(...)`. Should not be necessary IMO.

**Comment by sbrannen** [comment] 2017-09-10 15:28
First and foremost... cool that you're using the `SpringExension` with Spring Boot! 👍 

Secondly, I am aware of this issue and agree with you: it should not be _necessary_, but for the time being it is.

This is actually a duplicate of #8, and I've already started experimenting with a solution in conjunction with [SPR-15366](https://jira.spring.io/browse/SPR-15366).

In my branch for SPR-15366, I actually already have your particular scenario resolved (at least for `@ContextConfiguration`), but the _solution_ is turning out to be more involved than I had hoped.

As you can see in the description of SPR-15366, there are more than 10 annotations which will have to be looked up with special semantics now, and since these _special semantics_ are not supported by Core Spring itself... the _Spring TestContext Framework_ has to do all of the heavy lifting to make this happen -- and there's a lot of _magic_ regarding "inheritance" and merging of configuration attributes.

With that last point in mind, I'm afraid that this support will likely never make it into a Spring Framework 4.3.x release. Rather, it will likely only be available in a Spring Framework 5.x release.

I am therefore closing this issue in this repo.

**Closed as completed by sbrannen** 2017-09-10 15:28 UTC
